# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
# Copyright (C) Dassault Systemes - 2022 - Clement DAVID
#
#
# This YAML file describe the postbuild stage of the CI. This stage is mostly
# optional and generate/build extra documentation from Scilab build.
#


# build javadoc
build_javadoc:
  stage: postbuild
  tags: [x86_64-linux-gnu, docker, scilab]
  image: docker.io/openjdk:8-jdk-alpine
  variables:
      GIT_CLEAN_FLAGS: none
  dependencies: []
  script:
    - MASK="scilab/modules/*/src/java/";
    - MODULES=`ls -d $MASK`;
    - |
      LISTPKG="";
      for M in $MODULES; do
        LISTMODULES="$M:$LISTMODULES";
        MODULE=$(echo $M|cut -d/ -f3);
        LISTPKG="$LISTPKG org.scilab.modules.$MODULE";
      done;
    - javadoc -d public/javadoc -sourcepath $LISTMODULES $LISTPKG
  artifacts:
    paths:
      - public
  when: manual


# build Doxygen
build_doxygen:
  stage: postbuild
  tags: [x86_64-linux-gnu, docker, scilab]
  image: docker.io/tsgkadot/docker-doxygen
  variables:
      GIT_CLEAN_FLAGS: none
  dependencies: []
  script:
    - rm -fr $CI_PROJECT_DIR/public
    - cd scilab
    - mkdir reports
    - doxygen modules/development_tools/etc/doxyfile >/dev/null
    - mv reports/html $CI_PROJECT_DIR/public/doxygen
  artifacts:
    when: always
    paths:
      - public
  when: manual


# build preview of help.scilab.org
build_help_web:
  stage: postbuild
  tags: [x86_64-linux-gnu, docker, scilab]
  variables:
      GIT_CLEAN_FLAGS: none
  script:
    - rm -fr $CI_PROJECT_DIR/public
    - cd scilab
    - make doc-web
    - "[ ! -d public ] && mkdir public"
    - mv modules/helptools/web $CI_PROJECT_DIR/public/webdocs
  artifacts:
    paths:
      - public
  when: manual


# extract jar content to web
publish_help_jar:
  stage: postbuild
  tags: [x86_64-linux-gnu, docker, scilab]
  variables:
      GIT_STRATEGY: none
  needs:
    - x86_64-linux-gnu_build_branch
    - x86_64-linux-gnu_set_branch_env
  script:
    - echo "help from ${SCI_VERSION_STRING} ${ARCH}"
    - rm -fr $CI_PROJECT_DIR/public
    - "[ ! -d public ] && mkdir public"
    - "[ ! -d public/docs ] && mkdir public/docs"
    - cd public/docs
    - tar --wildcards --strip-components 6 -xJf ../../${SCI_VERSION_STRING}.bin.${ARCH}.tar.xz ${SCI_VERSION_STRING}/share/scilab/modules/helptools/jar/scilab_*_help.jar
    - for f in *.jar; do jar xf $f; done
    - rm *.jar
    - tar --strip-components 6 -xJf ../../${SCI_VERSION_STRING}.bin.${ARCH}.tar.xz ${SCI_VERSION_STRING}/share/scilab/modules/helptools/jar/scilab_images.jar
    - "[ ! -d images ] && mkdir images"
    - jar xf scilab_images.jar -d images/
    - rm scilab_images.jar
    - sed -i -e "s#jarsci:./#../images/#g" */*.html
  artifacts:
    paths:
      - public

sign_tool:
  stage: postbuild
  tags: [x64_windows, scilab]
  variables:
      GIT_STRATEGY: none
  script:
    - REM TODO how to sign ? was
    - REM call d:\signtool_password.bat
    - REM "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /f D:\\ESIGroupCERT.pfx /p "%SIGNPASS%" /t http://timestamp.sectigo.com /v %SCI_VERSION_STRING%_%ARCH%.exe
  needs:
    - x64_windows_build_branch
    - x64_windows_set_branch_env
  artifacts:
    paths:
      - $SCI_VERSION_STRING_$ARCH.exe
  when: manual
