# build javadoc
build_javadoc:
  stage: postbuild
  tags: ["docker"]
  image: docker.io/openjdk:8-jdk-alpine
  dependencies: []
  script:
    - MASK="scilab/modules/*/src/java/";
    - MODULES=`ls -d $MASK`;
    - |
      LISTPKG="";
      for M in $MODULES; do
        LISTMODULES="$M:$LISTMODULES";
        MODULE=$(echo $M|cut -d/ -f3);
        LISTPKG="$LISTPKG org.scilab.modules.$MODULE";
      done;
    - javadoc -d public/javadoc -sourcepath $LISTMODULES $LISTPKG
  artifacts:
    paths:
      - public
  when: manual


# build Doxygen
build_doxygen:
  stage: postbuild
  tags: ["docker"]
  image: docker.io/tsgkadot/docker-doxygen
  variables:
      GIT_STRATEGY: none
  dependencies: []
  script:
    - cd scilab
    - mkdir reports
    - doxygen modules/development_tools/etc/doxyfile >/dev/null
    - mv reports/html $CI_PROJECT_DIR/public/doxygen
  artifacts:
    when: always
    paths:
      - public
  when: manual


# build preview of help.scilab.org
build_help_web:
  stage: postbuild
  tags:
    - x86_64-linux-gnu
    - scilab
  variables:
      GIT_CLEAN_FLAGS: none
  script:
    - cd scilab
    - make doc-web
    - "[ ! -d public ] && mkdir public"
    - mv modules/helptools/web $CI_PROJECT_DIR/public/docs
  artifacts:
    paths:
      - public
  when: manual


# extract jar content to web
publish_help_jar:
  stage: postbuild
  tags:
    - x86_64-linux-gnu
    - scilab
  variables:
      GIT_STRATEGY: none
  needs:
    - x86_64-linux-gnu_build_branch
    - x86_64-linux-gnu_set_branch_env
  script:
    - echo "help from ${SCI_VERSION_STRING} ${ARCH}"
    - "[ ! -d public ] && mkdir public"
    - "[ ! -d public/docs ] && mkdir public/docs"
    - cd public/docs
    - tar --wildcards --strip-components 6 -xzf ../../${SCI_VERSION_STRING}.bin.${ARCH}.tar.gz ${SCI_VERSION_STRING}/share/scilab/modules/helptools/jar/scilab_*_help.jar
    - for f in *.jar; do unzip $f; done
    - rm *.jar
    - tar --strip-components 6 -xzf ../../${SCI_VERSION_STRING}.bin.${ARCH}.tar.gz ${SCI_VERSION_STRING}/share/scilab/modules/helptools/jar/scilab_images.jar
    - "[ ! -d images ] && mkdir images"
    - unzip scilab_images.jar -d images/
    - rm scilab_images.jar
    - sed -i -e "s#jarsci:./#../images/#g" */*.html
  artifacts:
    paths:
      - public
