# build javadoc
build_javadoc:
  stage: postbuild
  tags: ["docker"]
  image: docker.io/openjdk:8-jdk-alpine
  script:
    - MASK="scilab/modules/*/src/java/";
    - MODULES=`ls -d $MASK`;
    - |
      LISTPKG="";
      for M in $MODULES; do
        LISTMODULES="$M:$LISTMODULES";
        MODULE=$(echo $M|cut -d/ -f3);
        LISTPKG="$LISTPKG org.scilab.modules.$MODULE";
      done;
    - javadoc -d public/javadoc -sourcepath $LISTMODULES $LISTPKG |true
  artifacts:
    paths:
      - public
  when: manual


# build Doxygen
build_doxygen:
  stage: postbuild
  tags: ["docker"]
  image: docker.io/tsgkadot/docker-doxygen
  script:
    - cd scilab
    - mkdir reports
    - doxygen scilab/modules/development_tools/etc/doxyfile >/dev/null
    - mv reports/html $CI_PROJECT_DIR/public/doxygen
  artifacts:
    paths:
      - public
  when: manual


# build preview of help.scilab.org
build_help_web:
  stage: postbuild
  tags:
    - linux x86_64
    - scilab
  variables:
      GIT_CLEAN_FLAGS: none
  script:
    - cd scilab
    - make doc-web
    - mv modules/helptools/web $CI_PROJECT_DIR/public/docs
  artifacts:
    paths:
      - public
  when: manual

