test windows x64:
  stage: tests
  tags:
    - windows
  script:
    - echo "This job runs the test stage within windows".

  
test linux x86_64:
  stage: tests
  tags:
    - linux
  script:
    - echo "This job runs the test stage within linux".